[build]
  command = "yarn build"
  publish = "out"

[build.environment]
  NEXT_IMAGE_ALLOWED_DOMAINS="randomuser.me"
  FORCE_WEBP_OUTPUT = "true"
  NODE_VERSION = "12.18.2"
  YARN_VERSION = "1.19.1"
  NETLIFY_USE_YARN = "true"
  NEXT_SERVERLESS = "true"